package com.hsteinmetz.jstove.api.except;

/**
 * @author Hendrik Steinmetz
 */
public enum RecipeParseErrorCode {
  NO_RECIPE_NODE,
  MULTIPLE_RECIPE_NODES,
  FIELD_UNSUPPORTED_SHAPE,
  FIELD_EXPECTED_TEXT,
  DURATION_INVALID,
  RECIPE_NORMALIZATION_FAILED,
  EMPTY_INGREDIENT_LIST,
  EMPTY_INSTRUCTION_LIST,
  NO_INSTRUCTION_NODE,
  INVALID_INSTRUCTION_STEP,
}
